apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpi
spec:
  selector:
    matchLabels:
      app: bpi
  template:
    metadata:
      labels:
        app: bpi
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: api
        image: bpi-api-amd64:1.0
        env:
        - name: bpi_DGRAPH_URL
          valueFrom:
            configMapKeyRef:
              name: bpi
              key: dgraph_url
        - name: bpi_API_KEYS_MAPS_KEY
          valueFrom:
            configMapKeyRef:
              name: bpi
              key: map_key
        ports:
        - name: api
          containerPort: 3000
        - name: api-debug
          containerPort: 4000
        readinessProbe:
          httpGet:
            path: /v1/readiness
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 15
      - name: ui
        image: bpi-ui-amd64:1.0
        env:
        - name: bpi_DGRAPH_URL
          valueFrom:
            configMapKeyRef:
              name: bpi
              key: dgraph_url
        - name: bpi_API_KEYS_MAPS_KEY
          valueFrom:
            configMapKeyRef:
              name: bpi
              key: map_key
        ports:
        - name: ui
          containerPort: 80
        - name: ui-debug
          containerPort: 4080
        readinessProbe:
          httpGet:
            path: /debug/readiness
            port: 4080
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: bpi
spec:
  selector:
    service: bpi
  ports:
  - name: ui
    port: 80
    targetPort: ui
  - name: ui-debug
    port: 4080
    targetPort: ui-debug
