version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  travel-api:
    container_name: travel-api
    networks:
      - shared-network
    image: travel-api-amd64:1.0
    ports:
      - 3000:3000 # API
      - 4000:4000 # DEBUG API

  travel-ui:
    container_name: travel-ui
    networks:
      - shared-network
    image: travel-ui-amd64:1.0
    ports:
      - 80:80 # API
      - 4080:4080 # DEBUG API
