version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  bpi-api:
    container_name: bpi-api
    networks:
      - shared-network
    image: bpi-api-amd64:1.0
    ports:
      - 3000:3000 # API
      - 4000:4000 # DEBUG API

  bpi-ui:
    container_name: bpi-ui
    networks:
      - shared-network
    image: bpi-ui-amd64:1.0
    ports:
      - 80:80 # API
      - 4080:4080 # DEBUG API
