apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpi-api
spec:
  selector:
    matchLabels:
      app: bpi-api
  template:
    metadata:
      labels:
        app: bpi-api
    spec:
      containers:
      - name: app
        image: gcr.io/bpi/bpi-api-amd64:1.0
      - name: metrics
        image: gcr.io/bpi/metrics-amd64:1.0
